### ISSUE TITLE
Documentation: Restructure Storybook documentation

### ISSUE THREAD

**Issue by silentHoo** [inovex/elements#262]
We use Storybook to generate the documentation. This approach is now used for over two years. In the meantime Storybook introduced a new documentation format called MDX.

We saw that we need to put much effort in maintaining the documentation and the overall experience from a developer perspective could be much better as it is. Additionally the documentation is a bit unstructured and grown over time. We need to refactor and sort out some old docs and replace it with more structure.

- [ ] Think about how we need to restructure the documentation.
  - [ ] Check the possibilities MDX give us.
  - [ ] Propose the new concept in an GitHub issue and discuss your idea with the team.
  - [ ] Change the docs for one component only to demonstrate the new concept.

A first idea for a good structure could be:
1. One page with general info about the component itself.
2. One page with code examples for all specific frameworks (with a select control to choose the framework).
3. API documentation for events, props and css custom properties.

**Comment by janivo** [comment]
I did some research and came up with the following PR to simplify our stories: https://github.com/inovex/elements/pull/490

All stories should follow the `<ino-checkbox>` example story. 
This way of writing our stories allows us:
- to use typings in our stories which results in fewer errors
- to write less because we can reuse templates
- to include our description in the stories instead of having a README and a story for each component
