### ISSUE TITLE
ino-tab-bar: configure autofocus on activate

### ISSUE THREAD

**Issue by BenPag** [inovex/elements#400]
### Feature Request
In some cases it is necessary to control the autofocus mechanism of the tab bar, e.g. to keep the focus on the nav-drawer element.

### Description of the proposed solution

Provide the interface of MDCTabBar `focusOnActivate` for ino-tab-bar.
https://material.io/develop/web/supporting/tab-bar

### Additional context

If the ino-tab-bar is used in comparision to the nav-drawer the focus is immediatly set to the tab-bar after navigation. In order prevent a11y issues the focus shift should not be forced by component default.

**Comment by janivo** [comment]
this seems to be related to #196

**Comment by BenPag** [comment]
right, then I close this issue

**Comment by janivo** [comment]
I think we should leave both of them open because they are two different issues, but they affect the same functionality. In my opinion, they should be addressed in two separate pull requests so that our changelog looks like this:
- fix(...): fix autofocus on mount
- feat(...): add `autofocus` property
