### ISSUE TITLE
ino-switch: can't use two or more switches on one page

### ISSUE THREAD

**Issue by Sl1nd** [inovex/elements#524]
### Bug Report

Multiple ino-switch components can not be used on one page. Only the first switch works as expected. The followed switches do not change their own checked state but mutate the checked state of the first switch as well.   
### Possible Solution

It turned out that the MDC Switch instance is instantiated based on the `.mdc-switch` class. If multiple classes are present the querySelection references the first item on page.

**Comment by janivo** [comment]
https://github.com/inovex/elements/blob/34aeabdd0afe77bd2c263df237a7e7af22c7fe74/packages/elements/src/components/ino-switch/ino-switch.tsx#L65

This line seems to be the reason for this bug. It should be `this.el.querySelector(...)` instead of `document`.
I'm currently working on the switch in order to upgrade it to the new MDC Version so I'll implement these changes.
