### ISSUE TITLE
ino-switch: disabled state not displaying properly

### ISSUE THREAD

**Issue by BingeCode** [inovex/elements#972]
This is the default look

![Image](https://user-images.githubusercontent.com/48513535/244438107-d5dd3f5a-3076-40e0-9c81-537b23756687.png)

This is the current disabled state (triggered by using the `disabled` flag on the `InoSwitch `element)
EDIT: This only happens when the state is `EN`

![Image](https://user-images.githubusercontent.com/48513535/244438393-6d886aa7-e045-4ace-9210-d1b190f9f9e6.png)

This is what it should look like

![Image](https://user-images.githubusercontent.com/48513535/244438549-84a72117-b614-4f40-8857-c8d803f4551b.png)

The issue is resolved when the checked attribute is removed from the DOM element.
But the component also adds the `ino-switch-icon-disabled` twice.

![Image](https://user-images.githubusercontent.com/48513535/244439097-d1b189e7-6469-408b-b569-4458b1c1d54b.png)

Most likely the whole component display logic needs a refactor to improve stability.

**Comment by TobiasHeimGalindo** [comment]
Due to the issue from the sprint: I can't seem to recreate the transparent `disabled-track-color` problem. I have confirmed that it works in various browsers, as well as on our landing page and in Storybook. 

![Image](https://github.com/inovex/elements/assets/81302108/c2d52e50-c70c-4653-8939-706ea1800d9f)
